### ISSUE TITLE
Add NFT (scope) APIs

### ISSUE THREAD

**Issue by crussell-figure** [provenance-io/explorer-service#29]
## Summary

Add API functionality to show NFTs. 

## Problem Definition

Needed to incorporate Figure contracts (scopes) into the explorer platform.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by crussell-figure** [comment]
```
Assets
- list of assets
  - shows name, supply, owner

Per Asset
- the Asset
- In Escrow
  - Fungible Tokens (denoms like nhash) 
  	- header with count
  		-> takes you to listview filtered by that type and asset value owner
    		-> record takes you to the NFT page
  - Non-Fungible Tokens (scopes)
    - broken down by type? with count 
    	-> takes you to listview filtered by that type and asset value owner
    		-> record takes you to the NFT page
- holders
- coin transactions
  - transfers
- management transactions
  - mint/burn/ admin txs

Per NFT (NEW PAGE)
- the NFT
- whatever is under the NFA (I dont know yet)
- NFT transactions
  - again no clue what this would look like

Non-Fungible Token - NFT (NEW PAGE)
- list of NFTs 
```

**Comment by iramiller** [comment]
>Per NFT (NEW PAGE)
> - the NFT
>    - whatever is under the NFA (I dont know yet)
On a given NFT we have a list of current records and possible records (as derived from the scope/contract specifications assigned to the NFT.  It isn't really clear to me how "clean" this data is when viewed from a user browsing the explorer point of view vs the developer/program interpreting it.  We will simply need to see more test data roll in to know for sure.  Some of the test data is also likely to evolve a bit once people actually have a tangible view of what is actually going on chain.  To date most users of P8e care very little about exactly what goes on chain because there are so many layers of abstraction between what they are using and what is written.
